resolver: lts-22.44
compiler: ghc-9.6.7

packages:
- .

  # ghc-options:
  #   "$locals": -funbox-strict-fields -funfolding-use-threshold=16 -fexcess-precision -optc-O3 -optc-ffast-math -O2 -v

# extra-deps: []
