resolver: lts-17.4
compiler: ghc-8.10.4

packages:
- .

  # ghc-options:
  #   "$locals": -funbox-strict-fields -funfolding-use-threshold=16 -fexcess-precision -optc-O3 -optc-ffast-math -O2 -v

# extra-deps: []
